"""empty message

Revision ID: d7c3a791215b
Revises: 
Create Date: 2024-04-25 10:10:08.731251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c3a791215b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('regNo', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('regNo', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patients_id', sa.Integer(), nullable=True),
    sa.Column('doctors_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctors_id'], ['doctors.id'], name=op.f('fk_appointments_doctors_id_doctors')),
    sa.ForeignKeyConstraint(['patients_id'], ['patients.id'], name=op.f('fk_appointments_patients_id_patients')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('doctors_id', sa.Integer(), nullable=True),
    sa.Column('patients_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_treatments_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['doctors_id'], ['doctors.id'], name=op.f('fk_treatments_doctors_id_doctors')),
    sa.ForeignKeyConstraint(['patients_id'], ['patients.id'], name=op.f('fk_treatments_patients_id_patients')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatments')
    op.drop_table('appointments')
    op.drop_table('patients')
    op.drop_table('doctors')
    # ### end Alembic commands ###
